// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_NXXm8G6q--52KMEWHK3jQ87boACxo6A',
    appId: '1:636086890242:web:19dd06f51ea7e532d11c1b',
    messagingSenderId: '636086890242',
    projectId: 'mh-chatbot-4308e',
    authDomain: 'mh-chatbot-4308e.firebaseapp.com',
    storageBucket: 'mh-chatbot-4308e.firebasestorage.app',
    measurementId: 'G-4N44EE3SKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9R56Nf9f-QZNMxSOgI-w4Np-t64cQ_IY',
    appId: '1:636086890242:android:a07965b083a50c50d11c1b',
    messagingSenderId: '636086890242',
    projectId: 'mh-chatbot-4308e',
    storageBucket: 'mh-chatbot-4308e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy5VGJRzy0HLl0JEarhGRLF7EHVdudEjw',
    appId: '1:636086890242:ios:a9781b86fff1fedad11c1b',
    messagingSenderId: '636086890242',
    projectId: 'mh-chatbot-4308e',
    storageBucket: 'mh-chatbot-4308e.firebasestorage.app',
    androidClientId: '636086890242-1achdvek17iebgmdigqlbh9ad4c5u3fe.apps.googleusercontent.com',
    iosClientId: '636086890242-6fks503204ljjs6ng7merp8j6geobura.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy5VGJRzy0HLl0JEarhGRLF7EHVdudEjw',
    appId: '1:636086890242:ios:a9781b86fff1fedad11c1b',
    messagingSenderId: '636086890242',
    projectId: 'mh-chatbot-4308e',
    storageBucket: 'mh-chatbot-4308e.firebasestorage.app',
    androidClientId: '636086890242-1achdvek17iebgmdigqlbh9ad4c5u3fe.apps.googleusercontent.com',
    iosClientId: '636086890242-6fks503204ljjs6ng7merp8j6geobura.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_NXXm8G6q--52KMEWHK3jQ87boACxo6A',
    appId: '1:636086890242:web:c00e5f22ff5898d4d11c1b',
    messagingSenderId: '636086890242',
    projectId: 'mh-chatbot-4308e',
    authDomain: 'mh-chatbot-4308e.firebaseapp.com',
    storageBucket: 'mh-chatbot-4308e.firebasestorage.app',
    measurementId: 'G-1FE79YBQTQ',
  );

}